Incidents filters
openshift/monitoring-plugin pull request #182
Opened 2024-09-10 08:16 UTC by Fewwy

1. Added 2 filters above the charts
2. Implemented date range filter functionality. Depending on the chosen date range we adjust the graphs and fetch the data for both incidents and alerts
3. Still working on the other filter
4. Removed unused pieces of code, cleaned up functions, and added 1 utils function
5. Adjusted chart tooltip component - incidents ID is too long and was breaking the frame of the tooltip.

![image](https://github.com/user-attachments/assets/f6752348-74fa-4017-8df1-f24b64f0c84f)

2024-09-10 13:05 UTC, PeterYurkovich requested changes

2024-09-10 13:05 UTC, PeterYurkovich commented on src/components/Incidents/IncidentsPage.jsx
> +  const [defaultDaysSpan] = React.useState('7d');
This doesn't need to be a piece of react state since it is immutable

2024-09-10 13:05 UTC, PeterYurkovich commented on src/components/Incidents/IncidentsPage.jsx
> +          setIsLoading(false);
If this loading variable is only tracking the incidents fetch call and not the alert one this could we name it incidentsLoading or something similar? Also is there a need to have 2 separate loading states (incidents and alerting)?

This isn't needed for this PR, but with the size of these useEffects, and especially if they both want to have a loading state, it may be time to consider swapping them to custom hooks ([example](https://github.com/openshift/monitoring-plugin/blob/main/web/src/components/hooks/useURLPoll.ts)) for brevity of this component

2024-09-11 11:05 UTC, Fewwy commented on src/components/Incidents/IncidentsPage.jsx
> +  const [defaultDaysSpan] = React.useState('7d');
True, removed it

2024-09-11 11:07 UTC, Fewwy commented on src/components/Incidents/IncidentsPage.jsx
> +          setIsLoading(false);
Yes, that would be nice to do, I will write down a task for myself to refactor it like that

2024-09-11 11:51 UTC, PeterYurkovich commented
/lgtm

2024-09-11 11:51 UTC, merged