OCPBUGS-41206: use monospace for tables values for better identification
openshift/monitoring-plugin pull request #199
Opened 2024-09-26 08:27 UTC by jgbernalp

This pr adds monospace as the default font family for tables so values can be identified better

![Screenshot 2024-09-26 at 10 26 47](https://github.com/user-attachments/assets/b12fa6aa-1b0c-4abb-b2e7-d25f96153760)

2024-09-26 08:28 UTC, jgbernalp commented
/jira refresh

2024-09-26 11:15 UTC, jgbernalp commented
/retest-required

2024-09-26 12:46 UTC, PeterYurkovich requested changes

2024-09-26 12:46 UTC, PeterYurkovich commented on web/src/components/_monitoring.scss
> +  font-family: monospace;
The Patternfly docs ([1](https://www.patternfly.org/design-foundations/typography/#code), [2](https://pf5.patternfly.org/utility-classes/text)) mention the use of the RedHat Mono font to be used.

I believe that either `pf-v5-u-font-family-monospace`, `pf-v5-u-font-family-monospace-vf`, or `pf-v5-global--FontFamily--monospace` would be correct to use.

2024-09-26 13:32 UTC, jgbernalp commented on web/src/components/_monitoring.scss
> +  font-family: monospace;
Thnx for the comment, It seems the RedHat Mono is slightly different from the regular monospace. Is fixed now.

2024-09-26 15:48 UTC, PeterYurkovich commented
/lgtm

2024-09-26 16:06 UTC, PeterYurkovich commented
/retest

2024-09-26 21:05 UTC, PeterYurkovich commented
/retest

2024-09-26 21:13 UTC, PeterYurkovich commented
/retest

2024-09-26 22:09 UTC, zhuje commented
/retest

2024-09-26 22:38 UTC, zhuje commented
/retest

2024-09-27 01:32 UTC, zhuje commented
/test e2e-hypershift-conformance

2024-09-27 06:56 UTC, jgbernalp commented
/test e2e-hypershift-conformance

2024-09-27 07:02 UTC, jgbernalp commented
/test e2e-hypershift-conformance

2024-09-27 12:58 UTC, zhuje commented
/retest

2024-09-29 09:07 UTC, Tai-RedHat commented
PR tested with cluster-bot, font changed
/label qe-approved

2024-09-30 06:59 UTC, jgbernalp commented
/test e2e-hypershift-conformance

2024-09-30 10:32 UTC, jgbernalp commented
/test e2e-hypershift-conformance

2024-09-30 16:23 UTC, zhuje commented
/test e2e-hypershift-conformance

2024-10-01 01:01 UTC, zhuje commented
/test e2e-hypershift-conformance

2024-10-01 08:28 UTC, jgbernalp commented
/test e2e-hypershift-conformance

2024-10-01 14:58 UTC, merged