RHINENG-14585: Remove pending alerts from processing and add another value to the unique key
openshift/monitoring-plugin pull request #280
Opened 2024-12-03 17:34 UTC by Fewwy

https://issues.redhat.com/browse/RHINENG-14585

2024-12-03 18:24 UTC, zhuje commented
/ok-to-test

2024-12-03 18:44 UTC, zhuje commented
/lgtm

2024-12-03 21:00 UTC, falox requested changes

2024-12-03 21:00 UTC, falox commented on web/src/components/Incidents/processAlerts.js
> +  const filteredObjects = objects.filter((obj) => obj.metric.alertstate !== 'pending');
better `=== 'firing'`

2024-12-03 21:01 UTC, zhuje commented
/hold until response to https://github.com/openshift/monitoring-plugin/pull/280#discussion_r1868361230

2024-12-03 21:07 UTC, zhuje commented
/retest

2024-12-03 21:30 UTC, Fewwy commented on web/src/components/Incidents/processAlerts.js
> +  const filteredObjects = objects.filter((obj) => obj.metric.alertstate !== 'pending');
Done

2024-12-04 14:40 UTC, zhuje commented
/unhold because of resolved comment https://github.com/openshift/monitoring-plugin/pull/280#discussion_r1868392313

2024-12-04 14:40 UTC, zhuje commented
/lgtm

2024-12-04 18:41 UTC, zhuje commented
/unhold

2024-12-04 21:25 UTC, merged